"""Add Company model and link to Branch

Revision ID: 176fc7e07e35
Revises: e32343532b34
Create Date: 2026-05-06 10:26:54.527616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176fc7e07e35'
down_revision: Union[str, Sequence[str], None] = 'e32343532b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'branches', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_column('branches', 'company_id')
    # ### end Alembic commands ###
