"""Add hubtel_sender_id to Company

Revision ID: 2cbee4f87ebe
Revises: 176fc7e07e35
Create Date: 2026-05-07 12:56:27.668839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbee4f87ebe'
down_revision: Union[str, Sequence[str], None] = '176fc7e07e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('hubtel_sender_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'hubtel_sender_id')
    # ### end Alembic commands ###
