"""Add created_at to SMSLog

Revision ID: 8584a4e9b39c
Revises: baacf172d92b
Create Date: 2026-03-30 10:38:21.292441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8584a4e9b39c'
down_revision: Union[str, Sequence[str], None] = 'baacf172d92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_logs', 'created_at')
    # ### end Alembic commands ###
