"""Replace amount with items in Transaction

Revision ID: 9a77e4f6f1a1
Revises: 8584a4e9b39c
Create Date: 2026-03-30 11:50:41.175803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a77e4f6f1a1'
down_revision: Union[str, Sequence[str], None] = '8584a4e9b39c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('items', sa.Text(), nullable=True))
    op.drop_column('transactions', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'items')
    # ### end Alembic commands ###
