"""add is_bulk to sms_logs

Revision ID: a91d3584c24d
Revises: a725545ade26
Create Date: 2026-05-13 12:57:43.552744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91d3584c24d'
down_revision: Union[str, Sequence[str], None] = 'a725545ade26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_logs', sa.Column('is_bulk', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_logs', 'is_bulk')
    # ### end Alembic commands ###
