"""Make transaction_id optional in SMSLog

Revision ID: adb4ae27c327
Revises: 9a77e4f6f1a1
Create Date: 2026-03-30 12:17:58.503092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb4ae27c327'
down_revision: Union[str, Sequence[str], None] = '9a77e4f6f1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
