"""add_branch_id_to_smslog

Revision ID: e32343532b34
Revises: f74672b73145
Create Date: 2026-03-30 14:24:40.552429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32343532b34'
down_revision: Union[str, Sequence[str], None] = 'f74672b73145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_logs', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sms_logs', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sms_logs', type_='foreignkey')
    op.drop_column('sms_logs', 'branch_id')
    # ### end Alembic commands ###
